### ISSUE TITLE
Ruby 2.3.0 via RVM -  did_you_mean segmentation fault with roda

### ISSUE THREAD

**Issue by hirokiraj** [yuki24/did_you_mean#67] opened 2015-12-31 14:06 UTC
I recently started a project with ruby 2.3.0 shipped with did_you_mean, and was getting strange segmentation fault errors. Managed to replicate it in most simple scenario:

https://github.com/hirokiraj/roda-2.3.0-bug

It starts to normally suggest corrected method name, then after a few repetitions it crashes ruby

```
::1 - - [31/Dec/2015:14:47:51 +0100] "GET / HTTP/1.1" 500 61210 0.0197
/somefunnypath/.rvm/gems/ruby-2.3.0@global/gems/did_you_mean-1.0.0/lib/did_you_mean/spell_checkers/name_error_checkers/variable_name_checker.rb:10: [BUG] Segmentation fault at 0x000000000000c1
```

Control frame and backtrace -> https://gist.github.com/hirokiraj/83d917de90e0f60253ba
Crash diagnostic report -> https://gist.github.com/hirokiraj/4ef37abec72bec2f6ada

**Comment by yuki24** [comment] 2016-01-03 15:47
This seems more like a Ruby issue, so I'll file an issue on http://bugs.ruby-lang.org. Thank you for reporting!

cc/ @nobu @ko1

**Comment by hirokiraj** [comment] 2016-01-04 12:12
Can You provide direct link to the issue on Ruby bugtracker?

**Comment by yuki24** [comment] 2016-01-04 15:51
@hirokiraj I haven't created yet.

**Comment by yuki24** [comment] 2016-01-05 07:18
Someone else created an issue that looks quite similar to yours: https://bugs.ruby-lang.org/issues/11928

**Comment by tilthouse** [comment] 2016-01-12 23:52
FWIW, looks like this is fixed here https://bugs.ruby-lang.org/projects/ruby-trunk/repository/revisions/53514

**Comment by yuki24** [comment] 2016-02-01 10:46
I've confirmed that this bug has been fixed in [r53514](https://bugs.ruby-lang.org/projects/ruby-trunk/repository/revisions/53514) and [r53524](https://bugs.ruby-lang.org/projects/ruby-trunk/repository/revisions/53524).

@hirokiraj Thank you for reporting!

**Closed by yuki24** 2016-02-01 10:46 UTC

**Comment by wizardone** [comment] 2016-02-17 11:39
Might be a stupid question, but i also have the same issue with `2.3.0` and `rbenv`. Does the fact that this issues was fixed in some revision (not specific version) make it available to my current (and latest) version of ruby?

**Comment by tilthouse** [comment] 2016-02-17 19:21
Wondering if this has to wait for Ruby 2.3.1, or if there will be a patch release.

**Comment by yuki24** [comment] 2016-02-18 05:23
@wizardone not a stupid question at all! We'll be backporting the fix and releasing Ruby 2.3.1 soon. Stay tuned!

**Comment by wizardone** [comment] 2016-02-18 06:23
@yuki24 Great news! Thanks!

**Comment by jwaldrip** [comment] 2016-03-25 00:30
This is blocking us horribly, any update to when ruby 2.3.1 will be released?

**Comment by yuki24** [comment] 2016-05-09 10:45
Sorry for the late notice, but Ruby 2.3.1 has been released on April 26th and this issue should be gone now.

**Comment by santostiago** [comment] 2016-05-10 14:44
I'm still getting the same problem when using instance_variable_set and a nil value, on Ruby 2.3.1.

**Comment by vuquangtam** [comment] 2016-06-01 03:26
hi yuki, how to install the lastest 2.3.1 on raspberry pi.

**Comment by yuki24** [comment] 2016-06-01 11:22
@vuquangtam This is not a support forum and your question isn't about the did_you_mean gem. Would be nice if you could take time for a [quick google search](https://www.google.co.jp/#q=how+to+install+the+lastest+2.3.1+on+raspberry+pi).
